metadata:
  project: unifiedposepipeline
  repo_root_windows: "D:\\trials\\unifiedpipeline\\newrepo"
  repo_root_colab: "/content/unifiedposepipeline"
  default_branch: main
  last_updated_by: pradeepj247
  last_updated_on: "2025-12-28"

defaults:
  tracker: bytetrack
  reid_enabled: false
  reid_model: "models/reid/osnet_x0_25_msmt17.pt"
  detector_model: "models/yolo/yolov8s.pt"
  device: 0
  half: true
  processing_resolution: [1280, 720]
  max_frames: 600
  verbose: false
  preferred_video_filename: kohli_nets.mp4
  preferred_output_folder: demo_data/outputs/

paths:
  models_dir: "models"
  configs_dir: "configs"
  scripts:
    run_detector_tracking: "python run_detector_tracking.py --config {config_path} --no-visualization"
    setup_script: "setup/step2_install_models.py"

conventions:
  max_frames_is_config_only: true
  config_flag_names: ["--config", "--debug", "--no-visualization"]
  commit_message_prefix: "[assistant]"
  commit_policy_require_approval: true

quick_commands:
  pull_and_run_benchmark: "cd /content/unifiedposepipeline; git pull origin main; python run_detector_tracking.py --config configs/detect_track_new.yaml --no-visualization"

safety:
  files_to_not_edit:
    - "README.md"
    - ".github/**"
    - "setup/*.sh"
